[default]
registration_open = false
allow_anonymous = false

[apiserver]
bind = "0.0.0.0"
port = 9997
use_tls = false
# Use a decently secure secret. Obviously this needs to be changed :-).
session_secret = "OIJSDbeerdesOwshitvobkeshyijuchepavbiejCefJubemrirjOnJeutyucHalHushbo"

[database]
backend = "mysql"

[database.mysql]
username = "pasteuser"
password = "superSecretPassword"
hostname = "10.187.157.147"
database = "pastedb"

